/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modern.site.building.page.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.modern.site.building.page.model.MSBPageTemplate;
import com.liferay.modern.site.building.page.model.MSBPageTemplateModel;
import com.liferay.modern.site.building.page.model.MSBPageTemplateSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MSBPageTemplate service. Represents a row in the &quot;MSBPageTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MSBPageTemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MSBPageTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MSBPageTemplateImpl
 * @see MSBPageTemplate
 * @see MSBPageTemplateModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MSBPageTemplateModelImpl extends BaseModelImpl<MSBPageTemplate>
	implements MSBPageTemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a msb page template model instance should use the {@link MSBPageTemplate} interface instead.
	 */
	public static final String TABLE_NAME = "MSBPageTemplate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "msbPageTemplateId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "msbPageTemplateFolderId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("msbPageTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("msbPageTemplateFolderId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table MSBPageTemplate (uuid_ VARCHAR(75) null,msbPageTemplateId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,msbPageTemplateFolderId LONG)";
	public static final String TABLE_SQL_DROP = "drop table MSBPageTemplate";
	public static final String ORDER_BY_JPQL = " ORDER BY msbPageTemplate.msbPageTemplateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MSBPageTemplate.msbPageTemplateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.page.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.modern.site.building.page.model.MSBPageTemplate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.page.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.modern.site.building.page.model.MSBPageTemplate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.page.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.modern.site.building.page.model.MSBPageTemplate"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long MSBPAGETEMPLATEFOLDERID_COLUMN_BITMASK = 4L;
	public static final long NAME_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long MSBPAGETEMPLATEID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MSBPageTemplate toModel(MSBPageTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MSBPageTemplate model = new MSBPageTemplateImpl();

		model.setUuid(soapModel.getUuid());
		model.setMsbPageTemplateId(soapModel.getMsbPageTemplateId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setMsbPageTemplateFolderId(soapModel.getMsbPageTemplateFolderId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MSBPageTemplate> toModels(
		MSBPageTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MSBPageTemplate> models = new ArrayList<MSBPageTemplate>(soapModels.length);

		for (MSBPageTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.modern.site.building.page.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.modern.site.building.page.model.MSBPageTemplate"));

	public MSBPageTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _msbPageTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMsbPageTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _msbPageTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MSBPageTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return MSBPageTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("msbPageTemplateId", getMsbPageTemplateId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("msbPageTemplateFolderId", getMsbPageTemplateFolderId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long msbPageTemplateId = (Long)attributes.get("msbPageTemplateId");

		if (msbPageTemplateId != null) {
			setMsbPageTemplateId(msbPageTemplateId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long msbPageTemplateFolderId = (Long)attributes.get(
				"msbPageTemplateFolderId");

		if (msbPageTemplateFolderId != null) {
			setMsbPageTemplateFolderId(msbPageTemplateFolderId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMsbPageTemplateId() {
		return _msbPageTemplateId;
	}

	@Override
	public void setMsbPageTemplateId(long msbPageTemplateId) {
		_msbPageTemplateId = msbPageTemplateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public long getMsbPageTemplateFolderId() {
		return _msbPageTemplateFolderId;
	}

	@Override
	public void setMsbPageTemplateFolderId(long msbPageTemplateFolderId) {
		_columnBitmask |= MSBPAGETEMPLATEFOLDERID_COLUMN_BITMASK;

		if (!_setOriginalMsbPageTemplateFolderId) {
			_setOriginalMsbPageTemplateFolderId = true;

			_originalMsbPageTemplateFolderId = _msbPageTemplateFolderId;
		}

		_msbPageTemplateFolderId = msbPageTemplateFolderId;
	}

	public long getOriginalMsbPageTemplateFolderId() {
		return _originalMsbPageTemplateFolderId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				MSBPageTemplate.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MSBPageTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MSBPageTemplate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MSBPageTemplate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MSBPageTemplateImpl msbPageTemplateImpl = new MSBPageTemplateImpl();

		msbPageTemplateImpl.setUuid(getUuid());
		msbPageTemplateImpl.setMsbPageTemplateId(getMsbPageTemplateId());
		msbPageTemplateImpl.setGroupId(getGroupId());
		msbPageTemplateImpl.setCompanyId(getCompanyId());
		msbPageTemplateImpl.setUserId(getUserId());
		msbPageTemplateImpl.setUserName(getUserName());
		msbPageTemplateImpl.setCreateDate(getCreateDate());
		msbPageTemplateImpl.setModifiedDate(getModifiedDate());
		msbPageTemplateImpl.setName(getName());
		msbPageTemplateImpl.setMsbPageTemplateFolderId(getMsbPageTemplateFolderId());

		msbPageTemplateImpl.resetOriginalValues();

		return msbPageTemplateImpl;
	}

	@Override
	public int compareTo(MSBPageTemplate msbPageTemplate) {
		long primaryKey = msbPageTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MSBPageTemplate)) {
			return false;
		}

		MSBPageTemplate msbPageTemplate = (MSBPageTemplate)obj;

		long primaryKey = msbPageTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MSBPageTemplateModelImpl msbPageTemplateModelImpl = this;

		msbPageTemplateModelImpl._originalUuid = msbPageTemplateModelImpl._uuid;

		msbPageTemplateModelImpl._originalGroupId = msbPageTemplateModelImpl._groupId;

		msbPageTemplateModelImpl._setOriginalGroupId = false;

		msbPageTemplateModelImpl._originalCompanyId = msbPageTemplateModelImpl._companyId;

		msbPageTemplateModelImpl._setOriginalCompanyId = false;

		msbPageTemplateModelImpl._setModifiedDate = false;

		msbPageTemplateModelImpl._originalName = msbPageTemplateModelImpl._name;

		msbPageTemplateModelImpl._originalMsbPageTemplateFolderId = msbPageTemplateModelImpl._msbPageTemplateFolderId;

		msbPageTemplateModelImpl._setOriginalMsbPageTemplateFolderId = false;

		msbPageTemplateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MSBPageTemplate> toCacheModel() {
		MSBPageTemplateCacheModel msbPageTemplateCacheModel = new MSBPageTemplateCacheModel();

		msbPageTemplateCacheModel.uuid = getUuid();

		String uuid = msbPageTemplateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			msbPageTemplateCacheModel.uuid = null;
		}

		msbPageTemplateCacheModel.msbPageTemplateId = getMsbPageTemplateId();

		msbPageTemplateCacheModel.groupId = getGroupId();

		msbPageTemplateCacheModel.companyId = getCompanyId();

		msbPageTemplateCacheModel.userId = getUserId();

		msbPageTemplateCacheModel.userName = getUserName();

		String userName = msbPageTemplateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			msbPageTemplateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			msbPageTemplateCacheModel.createDate = createDate.getTime();
		}
		else {
			msbPageTemplateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			msbPageTemplateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			msbPageTemplateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		msbPageTemplateCacheModel.name = getName();

		String name = msbPageTemplateCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			msbPageTemplateCacheModel.name = null;
		}

		msbPageTemplateCacheModel.msbPageTemplateFolderId = getMsbPageTemplateFolderId();

		return msbPageTemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", msbPageTemplateId=");
		sb.append(getMsbPageTemplateId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", msbPageTemplateFolderId=");
		sb.append(getMsbPageTemplateFolderId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.modern.site.building.page.model.MSBPageTemplate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>msbPageTemplateId</column-name><column-value><![CDATA[");
		sb.append(getMsbPageTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>msbPageTemplateFolderId</column-name><column-value><![CDATA[");
		sb.append(getMsbPageTemplateFolderId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MSBPageTemplate.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MSBPageTemplate.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _msbPageTemplateId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private long _msbPageTemplateFolderId;
	private long _originalMsbPageTemplateFolderId;
	private boolean _setOriginalMsbPageTemplateFolderId;
	private long _columnBitmask;
	private MSBPageTemplate _escapedModel;
}