/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AssetEntryRel service. Represents a row in the &quot;AssetEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.asset.entry.rel.model.impl.AssetEntryRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.asset.entry.rel.model.impl.AssetEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryRel
 * @see com.liferay.asset.entry.rel.model.impl.AssetEntryRelImpl
 * @see com.liferay.asset.entry.rel.model.impl.AssetEntryRelModelImpl
 * @generated
 */
@ProviderType
public interface AssetEntryRelModel extends AttachedModel,
	BaseModel<AssetEntryRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry rel model instance should use the {@link AssetEntryRel} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry rel.
	 *
	 * @return the primary key of this asset entry rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry rel.
	 *
	 * @param primaryKey the primary key of this asset entry rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset entry rel ID of this asset entry rel.
	 *
	 * @return the asset entry rel ID of this asset entry rel
	 */
	public long getAssetEntryRelId();

	/**
	 * Sets the asset entry rel ID of this asset entry rel.
	 *
	 * @param assetEntryRelId the asset entry rel ID of this asset entry rel
	 */
	public void setAssetEntryRelId(long assetEntryRelId);

	/**
	 * Returns the asset entry ID of this asset entry rel.
	 *
	 * @return the asset entry ID of this asset entry rel
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset entry rel.
	 *
	 * @param assetEntryId the asset entry ID of this asset entry rel
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the fully qualified class name of this asset entry rel.
	 *
	 * @return the fully qualified class name of this asset entry rel
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset entry rel.
	 *
	 * @return the class name ID of this asset entry rel
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset entry rel.
	 *
	 * @param classNameId the class name ID of this asset entry rel
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this asset entry rel.
	 *
	 * @return the class pk of this asset entry rel
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this asset entry rel.
	 *
	 * @param classPK the class pk of this asset entry rel
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetEntryRel assetEntryRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetEntryRel> toCacheModel();

	@Override
	public AssetEntryRel toEscapedModel();

	@Override
	public AssetEntryRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}