/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modern.site.building.page.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MSBPageTemplateFolder service. Represents a row in the &quot;MSBPageTemplateFolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.modern.site.building.page.model.impl.MSBPageTemplateFolderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.modern.site.building.page.model.impl.MSBPageTemplateFolderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MSBPageTemplateFolder
 * @see com.liferay.modern.site.building.page.model.impl.MSBPageTemplateFolderImpl
 * @see com.liferay.modern.site.building.page.model.impl.MSBPageTemplateFolderModelImpl
 * @generated
 */
@ProviderType
public interface MSBPageTemplateFolderModel extends BaseModel<MSBPageTemplateFolder>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a msb page template folder model instance should use the {@link MSBPageTemplateFolder} interface instead.
	 */

	/**
	 * Returns the primary key of this msb page template folder.
	 *
	 * @return the primary key of this msb page template folder
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this msb page template folder.
	 *
	 * @param primaryKey the primary key of this msb page template folder
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this msb page template folder.
	 *
	 * @return the uuid of this msb page template folder
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this msb page template folder.
	 *
	 * @param uuid the uuid of this msb page template folder
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the msb page template folder ID of this msb page template folder.
	 *
	 * @return the msb page template folder ID of this msb page template folder
	 */
	public long getMsbPageTemplateFolderId();

	/**
	 * Sets the msb page template folder ID of this msb page template folder.
	 *
	 * @param msbPageTemplateFolderId the msb page template folder ID of this msb page template folder
	 */
	public void setMsbPageTemplateFolderId(long msbPageTemplateFolderId);

	/**
	 * Returns the group ID of this msb page template folder.
	 *
	 * @return the group ID of this msb page template folder
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this msb page template folder.
	 *
	 * @param groupId the group ID of this msb page template folder
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this msb page template folder.
	 *
	 * @return the company ID of this msb page template folder
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this msb page template folder.
	 *
	 * @param companyId the company ID of this msb page template folder
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this msb page template folder.
	 *
	 * @return the user ID of this msb page template folder
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this msb page template folder.
	 *
	 * @param userId the user ID of this msb page template folder
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this msb page template folder.
	 *
	 * @return the user uuid of this msb page template folder
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this msb page template folder.
	 *
	 * @param userUuid the user uuid of this msb page template folder
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this msb page template folder.
	 *
	 * @return the user name of this msb page template folder
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this msb page template folder.
	 *
	 * @param userName the user name of this msb page template folder
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this msb page template folder.
	 *
	 * @return the create date of this msb page template folder
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this msb page template folder.
	 *
	 * @param createDate the create date of this msb page template folder
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this msb page template folder.
	 *
	 * @return the modified date of this msb page template folder
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this msb page template folder.
	 *
	 * @param modifiedDate the modified date of this msb page template folder
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this msb page template folder.
	 *
	 * @return the name of this msb page template folder
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this msb page template folder.
	 *
	 * @param name the name of this msb page template folder
	 */
	public void setName(String name);

	/**
	 * Returns the description of this msb page template folder.
	 *
	 * @return the description of this msb page template folder
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this msb page template folder.
	 *
	 * @param description the description of this msb page template folder
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MSBPageTemplateFolder msbPageTemplateFolder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MSBPageTemplateFolder> toCacheModel();

	@Override
	public MSBPageTemplateFolder toEscapedModel();

	@Override
	public MSBPageTemplateFolder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}