/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.fragment.model.LayoutFragment;
import com.liferay.fragment.model.LayoutFragmentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LayoutFragment service. Represents a row in the &quot;LayoutFragment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LayoutFragmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutFragmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutFragmentImpl
 * @see LayoutFragment
 * @see LayoutFragmentModel
 * @generated
 */
@ProviderType
public class LayoutFragmentModelImpl extends BaseModelImpl<LayoutFragment>
	implements LayoutFragmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout fragment model instance should use the {@link LayoutFragment} interface instead.
	 */
	public static final String TABLE_NAME = "LayoutFragment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "layoutFragmentId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "plid", Types.BIGINT },
			{ "fragmentEntryId", Types.BIGINT },
			{ "css", Types.VARCHAR },
			{ "html", Types.VARCHAR },
			{ "js", Types.VARCHAR },
			{ "editableValues", Types.VARCHAR },
			{ "position", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("layoutFragmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("css", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("html", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("js", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("editableValues", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table LayoutFragment (layoutFragmentId LONG not null primary key,groupId LONG,plid LONG,fragmentEntryId LONG,css STRING null,html STRING null,js STRING null,editableValues STRING null,position INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table LayoutFragment";
	public static final String ORDER_BY_JPQL = " ORDER BY layoutFragment.position ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LayoutFragment.position ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.fragment.model.LayoutFragment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.fragment.model.LayoutFragment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.fragment.model.LayoutFragment"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long PLID_COLUMN_BITMASK = 2L;
	public static final long POSITION_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.fragment.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.fragment.model.LayoutFragment"));

	public LayoutFragmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutFragmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutFragmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutFragmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutFragment.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutFragment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("layoutFragmentId", getLayoutFragmentId());
		attributes.put("groupId", getGroupId());
		attributes.put("plid", getPlid());
		attributes.put("fragmentEntryId", getFragmentEntryId());
		attributes.put("css", getCss());
		attributes.put("html", getHtml());
		attributes.put("js", getJs());
		attributes.put("editableValues", getEditableValues());
		attributes.put("position", getPosition());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long layoutFragmentId = (Long)attributes.get("layoutFragmentId");

		if (layoutFragmentId != null) {
			setLayoutFragmentId(layoutFragmentId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long plid = (Long)attributes.get("plid");

		if (plid != null) {
			setPlid(plid);
		}

		Long fragmentEntryId = (Long)attributes.get("fragmentEntryId");

		if (fragmentEntryId != null) {
			setFragmentEntryId(fragmentEntryId);
		}

		String css = (String)attributes.get("css");

		if (css != null) {
			setCss(css);
		}

		String html = (String)attributes.get("html");

		if (html != null) {
			setHtml(html);
		}

		String js = (String)attributes.get("js");

		if (js != null) {
			setJs(js);
		}

		String editableValues = (String)attributes.get("editableValues");

		if (editableValues != null) {
			setEditableValues(editableValues);
		}

		Integer position = (Integer)attributes.get("position");

		if (position != null) {
			setPosition(position);
		}
	}

	@Override
	public long getLayoutFragmentId() {
		return _layoutFragmentId;
	}

	@Override
	public void setLayoutFragmentId(long layoutFragmentId) {
		_layoutFragmentId = layoutFragmentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_columnBitmask |= PLID_COLUMN_BITMASK;

		if (!_setOriginalPlid) {
			_setOriginalPlid = true;

			_originalPlid = _plid;
		}

		_plid = plid;
	}

	public long getOriginalPlid() {
		return _originalPlid;
	}

	@Override
	public long getFragmentEntryId() {
		return _fragmentEntryId;
	}

	@Override
	public void setFragmentEntryId(long fragmentEntryId) {
		_fragmentEntryId = fragmentEntryId;
	}

	@Override
	public String getCss() {
		if (_css == null) {
			return "";
		}
		else {
			return _css;
		}
	}

	@Override
	public void setCss(String css) {
		_css = css;
	}

	@Override
	public String getHtml() {
		if (_html == null) {
			return "";
		}
		else {
			return _html;
		}
	}

	@Override
	public void setHtml(String html) {
		_html = html;
	}

	@Override
	public String getJs() {
		if (_js == null) {
			return "";
		}
		else {
			return _js;
		}
	}

	@Override
	public void setJs(String js) {
		_js = js;
	}

	@Override
	public String getEditableValues() {
		if (_editableValues == null) {
			return "";
		}
		else {
			return _editableValues;
		}
	}

	@Override
	public void setEditableValues(String editableValues) {
		_editableValues = editableValues;
	}

	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		_columnBitmask = -1L;

		_position = position;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LayoutFragment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LayoutFragment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LayoutFragment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutFragmentImpl layoutFragmentImpl = new LayoutFragmentImpl();

		layoutFragmentImpl.setLayoutFragmentId(getLayoutFragmentId());
		layoutFragmentImpl.setGroupId(getGroupId());
		layoutFragmentImpl.setPlid(getPlid());
		layoutFragmentImpl.setFragmentEntryId(getFragmentEntryId());
		layoutFragmentImpl.setCss(getCss());
		layoutFragmentImpl.setHtml(getHtml());
		layoutFragmentImpl.setJs(getJs());
		layoutFragmentImpl.setEditableValues(getEditableValues());
		layoutFragmentImpl.setPosition(getPosition());

		layoutFragmentImpl.resetOriginalValues();

		return layoutFragmentImpl;
	}

	@Override
	public int compareTo(LayoutFragment layoutFragment) {
		int value = 0;

		if (getPosition() < layoutFragment.getPosition()) {
			value = -1;
		}
		else if (getPosition() > layoutFragment.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutFragment)) {
			return false;
		}

		LayoutFragment layoutFragment = (LayoutFragment)obj;

		long primaryKey = layoutFragment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LayoutFragmentModelImpl layoutFragmentModelImpl = this;

		layoutFragmentModelImpl._originalGroupId = layoutFragmentModelImpl._groupId;

		layoutFragmentModelImpl._setOriginalGroupId = false;

		layoutFragmentModelImpl._originalPlid = layoutFragmentModelImpl._plid;

		layoutFragmentModelImpl._setOriginalPlid = false;

		layoutFragmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutFragment> toCacheModel() {
		LayoutFragmentCacheModel layoutFragmentCacheModel = new LayoutFragmentCacheModel();

		layoutFragmentCacheModel.layoutFragmentId = getLayoutFragmentId();

		layoutFragmentCacheModel.groupId = getGroupId();

		layoutFragmentCacheModel.plid = getPlid();

		layoutFragmentCacheModel.fragmentEntryId = getFragmentEntryId();

		layoutFragmentCacheModel.css = getCss();

		String css = layoutFragmentCacheModel.css;

		if ((css != null) && (css.length() == 0)) {
			layoutFragmentCacheModel.css = null;
		}

		layoutFragmentCacheModel.html = getHtml();

		String html = layoutFragmentCacheModel.html;

		if ((html != null) && (html.length() == 0)) {
			layoutFragmentCacheModel.html = null;
		}

		layoutFragmentCacheModel.js = getJs();

		String js = layoutFragmentCacheModel.js;

		if ((js != null) && (js.length() == 0)) {
			layoutFragmentCacheModel.js = null;
		}

		layoutFragmentCacheModel.editableValues = getEditableValues();

		String editableValues = layoutFragmentCacheModel.editableValues;

		if ((editableValues != null) && (editableValues.length() == 0)) {
			layoutFragmentCacheModel.editableValues = null;
		}

		layoutFragmentCacheModel.position = getPosition();

		return layoutFragmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{layoutFragmentId=");
		sb.append(getLayoutFragmentId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", plid=");
		sb.append(getPlid());
		sb.append(", fragmentEntryId=");
		sb.append(getFragmentEntryId());
		sb.append(", css=");
		sb.append(getCss());
		sb.append(", html=");
		sb.append(getHtml());
		sb.append(", js=");
		sb.append(getJs());
		sb.append(", editableValues=");
		sb.append(getEditableValues());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.fragment.model.LayoutFragment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>layoutFragmentId</column-name><column-value><![CDATA[");
		sb.append(getLayoutFragmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>plid</column-name><column-value><![CDATA[");
		sb.append(getPlid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fragmentEntryId</column-name><column-value><![CDATA[");
		sb.append(getFragmentEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>css</column-name><column-value><![CDATA[");
		sb.append(getCss());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>html</column-name><column-value><![CDATA[");
		sb.append(getHtml());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>js</column-name><column-value><![CDATA[");
		sb.append(getJs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>editableValues</column-name><column-value><![CDATA[");
		sb.append(getEditableValues());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LayoutFragment.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LayoutFragment.class
		};
	private long _layoutFragmentId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _plid;
	private long _originalPlid;
	private boolean _setOriginalPlid;
	private long _fragmentEntryId;
	private String _css;
	private String _html;
	private String _js;
	private String _editableValues;
	private int _position;
	private long _columnBitmask;
	private LayoutFragment _escapedModel;
}