/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.page.template.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LayoutPageTemplateSetting service. Represents a row in the &quot;LayoutPageTemplateSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateSetting
 * @see com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingImpl
 * @see com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingModelImpl
 * @generated
 */
@ProviderType
public interface LayoutPageTemplateSettingModel extends AttachedModel,
	BaseModel<LayoutPageTemplateSetting>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout page template setting model instance should use the {@link LayoutPageTemplateSetting} interface instead.
	 */

	/**
	 * Returns the primary key of this layout page template setting.
	 *
	 * @return the primary key of this layout page template setting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout page template setting.
	 *
	 * @param primaryKey the primary key of this layout page template setting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this layout page template setting.
	 *
	 * @return the uuid of this layout page template setting
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this layout page template setting.
	 *
	 * @param uuid the uuid of this layout page template setting
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the layout page template setting ID of this layout page template setting.
	 *
	 * @return the layout page template setting ID of this layout page template setting
	 */
	public long getLayoutPageTemplateSettingId();

	/**
	 * Sets the layout page template setting ID of this layout page template setting.
	 *
	 * @param layoutPageTemplateSettingId the layout page template setting ID of this layout page template setting
	 */
	public void setLayoutPageTemplateSettingId(long layoutPageTemplateSettingId);

	/**
	 * Returns the group ID of this layout page template setting.
	 *
	 * @return the group ID of this layout page template setting
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this layout page template setting.
	 *
	 * @param groupId the group ID of this layout page template setting
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout page template setting.
	 *
	 * @return the company ID of this layout page template setting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout page template setting.
	 *
	 * @param companyId the company ID of this layout page template setting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this layout page template setting.
	 *
	 * @return the user ID of this layout page template setting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this layout page template setting.
	 *
	 * @param userId the user ID of this layout page template setting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layout page template setting.
	 *
	 * @return the user uuid of this layout page template setting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this layout page template setting.
	 *
	 * @param userUuid the user uuid of this layout page template setting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this layout page template setting.
	 *
	 * @return the user name of this layout page template setting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this layout page template setting.
	 *
	 * @param userName the user name of this layout page template setting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this layout page template setting.
	 *
	 * @return the create date of this layout page template setting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout page template setting.
	 *
	 * @param createDate the create date of this layout page template setting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout page template setting.
	 *
	 * @return the modified date of this layout page template setting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout page template setting.
	 *
	 * @param modifiedDate the modified date of this layout page template setting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this layout page template setting.
	 *
	 * @return the fully qualified class name of this layout page template setting
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this layout page template setting.
	 *
	 * @return the class name ID of this layout page template setting
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this layout page template setting.
	 *
	 * @param classNameId the class name ID of this layout page template setting
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this layout page template setting.
	 *
	 * @return the class pk of this layout page template setting
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this layout page template setting.
	 *
	 * @param classPK the class pk of this layout page template setting
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the settings of this layout page template setting.
	 *
	 * @return the settings of this layout page template setting
	 */
	@AutoEscape
	public String getSettings();

	/**
	 * Sets the settings of this layout page template setting.
	 *
	 * @param settings the settings of this layout page template setting
	 */
	public void setSettings(String settings);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LayoutPageTemplateSetting layoutPageTemplateSetting);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LayoutPageTemplateSetting> toCacheModel();

	@Override
	public LayoutPageTemplateSetting toEscapedModel();

	@Override
	public LayoutPageTemplateSetting toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}