/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modern.site.building.page.service.base;

import com.liferay.modern.site.building.page.model.MSBPageTemplate;
import com.liferay.modern.site.building.page.service.MSBPageTemplateService;
import com.liferay.modern.site.building.page.service.persistence.MSBPageTemplatePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the msb page template remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.modern.site.building.page.service.impl.MSBPageTemplateServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.modern.site.building.page.service.impl.MSBPageTemplateServiceImpl
 * @see com.liferay.modern.site.building.page.service.MSBPageTemplateServiceUtil
 * @generated
 */
public abstract class MSBPageTemplateServiceBaseImpl extends BaseServiceImpl
	implements MSBPageTemplateService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.modern.site.building.page.service.MSBPageTemplateServiceUtil} to access the msb page template remote service.
	 */

	/**
	 * Returns the msb page template local service.
	 *
	 * @return the msb page template local service
	 */
	public com.liferay.modern.site.building.page.service.MSBPageTemplateLocalService getMSBPageTemplateLocalService() {
		return msbPageTemplateLocalService;
	}

	/**
	 * Sets the msb page template local service.
	 *
	 * @param msbPageTemplateLocalService the msb page template local service
	 */
	public void setMSBPageTemplateLocalService(
		com.liferay.modern.site.building.page.service.MSBPageTemplateLocalService msbPageTemplateLocalService) {
		this.msbPageTemplateLocalService = msbPageTemplateLocalService;
	}

	/**
	 * Returns the msb page template remote service.
	 *
	 * @return the msb page template remote service
	 */
	public MSBPageTemplateService getMSBPageTemplateService() {
		return msbPageTemplateService;
	}

	/**
	 * Sets the msb page template remote service.
	 *
	 * @param msbPageTemplateService the msb page template remote service
	 */
	public void setMSBPageTemplateService(
		MSBPageTemplateService msbPageTemplateService) {
		this.msbPageTemplateService = msbPageTemplateService;
	}

	/**
	 * Returns the msb page template persistence.
	 *
	 * @return the msb page template persistence
	 */
	public MSBPageTemplatePersistence getMSBPageTemplatePersistence() {
		return msbPageTemplatePersistence;
	}

	/**
	 * Sets the msb page template persistence.
	 *
	 * @param msbPageTemplatePersistence the msb page template persistence
	 */
	public void setMSBPageTemplatePersistence(
		MSBPageTemplatePersistence msbPageTemplatePersistence) {
		this.msbPageTemplatePersistence = msbPageTemplatePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MSBPageTemplateService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MSBPageTemplate.class;
	}

	protected String getModelClassName() {
		return MSBPageTemplate.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = msbPageTemplatePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.modern.site.building.page.service.MSBPageTemplateLocalService.class)
	protected com.liferay.modern.site.building.page.service.MSBPageTemplateLocalService msbPageTemplateLocalService;
	@BeanReference(type = MSBPageTemplateService.class)
	protected MSBPageTemplateService msbPageTemplateService;
	@BeanReference(type = MSBPageTemplatePersistence.class)
	protected MSBPageTemplatePersistence msbPageTemplatePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}