logging.level.org.springframework.security=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.hibernate.type=INFO
management.endpoints.enabled-by-default=true
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health, info, metrics
server.port=8880
spring.application.name=saas-connector
spring.data.rest.basePath=/api