/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.page.template.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.layout.page.template.model.LayoutPageTemplateSetting;
import com.liferay.layout.page.template.service.LayoutPageTemplateSettingLocalService;
import com.liferay.layout.page.template.service.persistence.LayoutPageTemplateSettingPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the layout page template setting local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.page.template.service.impl.LayoutPageTemplateSettingLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.page.template.service.impl.LayoutPageTemplateSettingLocalServiceImpl
 * @see com.liferay.layout.page.template.service.LayoutPageTemplateSettingLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class LayoutPageTemplateSettingLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements LayoutPageTemplateSettingLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.layout.page.template.service.LayoutPageTemplateSettingLocalServiceUtil} to access the layout page template setting local service.
	 */

	/**
	 * Adds the layout page template setting to the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutPageTemplateSetting the layout page template setting
	 * @return the layout page template setting that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateSetting addLayoutPageTemplateSetting(
		LayoutPageTemplateSetting layoutPageTemplateSetting) {
		layoutPageTemplateSetting.setNew(true);

		return layoutPageTemplateSettingPersistence.update(layoutPageTemplateSetting);
	}

	/**
	 * Creates a new layout page template setting with the primary key. Does not add the layout page template setting to the database.
	 *
	 * @param layoutPageTemplateSettingId the primary key for the new layout page template setting
	 * @return the new layout page template setting
	 */
	@Override
	@Transactional(enabled = false)
	public LayoutPageTemplateSetting createLayoutPageTemplateSetting(
		long layoutPageTemplateSettingId) {
		return layoutPageTemplateSettingPersistence.create(layoutPageTemplateSettingId);
	}

	/**
	 * Deletes the layout page template setting with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutPageTemplateSettingId the primary key of the layout page template setting
	 * @return the layout page template setting that was removed
	 * @throws PortalException if a layout page template setting with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateSetting deleteLayoutPageTemplateSetting(
		long layoutPageTemplateSettingId) throws PortalException {
		return layoutPageTemplateSettingPersistence.remove(layoutPageTemplateSettingId);
	}

	/**
	 * Deletes the layout page template setting from the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutPageTemplateSetting the layout page template setting
	 * @return the layout page template setting that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateSetting deleteLayoutPageTemplateSetting(
		LayoutPageTemplateSetting layoutPageTemplateSetting) {
		return layoutPageTemplateSettingPersistence.remove(layoutPageTemplateSetting);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LayoutPageTemplateSetting.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return layoutPageTemplateSettingPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return layoutPageTemplateSettingPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return layoutPageTemplateSettingPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return layoutPageTemplateSettingPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return layoutPageTemplateSettingPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public LayoutPageTemplateSetting fetchLayoutPageTemplateSetting(
		long layoutPageTemplateSettingId) {
		return layoutPageTemplateSettingPersistence.fetchByPrimaryKey(layoutPageTemplateSettingId);
	}

	/**
	 * Returns the layout page template setting matching the UUID and group.
	 *
	 * @param uuid the layout page template setting's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template setting, or <code>null</code> if a matching layout page template setting could not be found
	 */
	@Override
	public LayoutPageTemplateSetting fetchLayoutPageTemplateSettingByUuidAndGroupId(
		String uuid, long groupId) {
		return layoutPageTemplateSettingPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the layout page template setting with the primary key.
	 *
	 * @param layoutPageTemplateSettingId the primary key of the layout page template setting
	 * @return the layout page template setting
	 * @throws PortalException if a layout page template setting with the primary key could not be found
	 */
	@Override
	public LayoutPageTemplateSetting getLayoutPageTemplateSetting(
		long layoutPageTemplateSettingId) throws PortalException {
		return layoutPageTemplateSettingPersistence.findByPrimaryKey(layoutPageTemplateSettingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(layoutPageTemplateSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutPageTemplateSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateSettingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(layoutPageTemplateSettingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LayoutPageTemplateSetting.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateSettingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(layoutPageTemplateSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutPageTemplateSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateSettingId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");

					StagedModelType stagedModelType = exportActionableDynamicQuery.getStagedModelType();

					long referrerClassNameId = stagedModelType.getReferrerClassNameId();

					Property classNameIdProperty = PropertyFactoryUtil.forName(
							"classNameId");

					if ((referrerClassNameId != StagedModelType.REFERRER_CLASS_NAME_ID_ALL) &&
							(referrerClassNameId != StagedModelType.REFERRER_CLASS_NAME_ID_ANY)) {
						dynamicQuery.add(classNameIdProperty.eq(
								stagedModelType.getReferrerClassNameId()));
					}
					else if (referrerClassNameId == StagedModelType.REFERRER_CLASS_NAME_ID_ANY) {
						dynamicQuery.add(classNameIdProperty.isNotNull());
					}
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<LayoutPageTemplateSetting>() {
				@Override
				public void performAction(
					LayoutPageTemplateSetting layoutPageTemplateSetting)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						layoutPageTemplateSetting);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(
					LayoutPageTemplateSetting.class.getName()),
				StagedModelType.REFERRER_CLASS_NAME_ID_ALL));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return layoutPageTemplateSettingLocalService.deleteLayoutPageTemplateSetting((LayoutPageTemplateSetting)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return layoutPageTemplateSettingPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the layout page template settings matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template settings
	 * @param companyId the primary key of the company
	 * @return the matching layout page template settings, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateSetting> getLayoutPageTemplateSettingsByUuidAndCompanyId(
		String uuid, long companyId) {
		return layoutPageTemplateSettingPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of layout page template settings matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template settings
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of layout page template settings
	 * @param end the upper bound of the range of layout page template settings (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching layout page template settings, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateSetting> getLayoutPageTemplateSettingsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<LayoutPageTemplateSetting> orderByComparator) {
		return layoutPageTemplateSettingPersistence.findByUuid_C(uuid,
			companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the layout page template setting matching the UUID and group.
	 *
	 * @param uuid the layout page template setting's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template setting
	 * @throws PortalException if a matching layout page template setting could not be found
	 */
	@Override
	public LayoutPageTemplateSetting getLayoutPageTemplateSettingByUuidAndGroupId(
		String uuid, long groupId) throws PortalException {
		return layoutPageTemplateSettingPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the layout page template settings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.layout.page.template.model.impl.LayoutPageTemplateSettingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of layout page template settings
	 * @param end the upper bound of the range of layout page template settings (not inclusive)
	 * @return the range of layout page template settings
	 */
	@Override
	public List<LayoutPageTemplateSetting> getLayoutPageTemplateSettings(
		int start, int end) {
		return layoutPageTemplateSettingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of layout page template settings.
	 *
	 * @return the number of layout page template settings
	 */
	@Override
	public int getLayoutPageTemplateSettingsCount() {
		return layoutPageTemplateSettingPersistence.countAll();
	}

	/**
	 * Updates the layout page template setting in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param layoutPageTemplateSetting the layout page template setting
	 * @return the layout page template setting that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateSetting updateLayoutPageTemplateSetting(
		LayoutPageTemplateSetting layoutPageTemplateSetting) {
		return layoutPageTemplateSettingPersistence.update(layoutPageTemplateSetting);
	}

	/**
	 * Returns the layout page template setting local service.
	 *
	 * @return the layout page template setting local service
	 */
	public LayoutPageTemplateSettingLocalService getLayoutPageTemplateSettingLocalService() {
		return layoutPageTemplateSettingLocalService;
	}

	/**
	 * Sets the layout page template setting local service.
	 *
	 * @param layoutPageTemplateSettingLocalService the layout page template setting local service
	 */
	public void setLayoutPageTemplateSettingLocalService(
		LayoutPageTemplateSettingLocalService layoutPageTemplateSettingLocalService) {
		this.layoutPageTemplateSettingLocalService = layoutPageTemplateSettingLocalService;
	}

	/**
	 * Returns the layout page template setting persistence.
	 *
	 * @return the layout page template setting persistence
	 */
	public LayoutPageTemplateSettingPersistence getLayoutPageTemplateSettingPersistence() {
		return layoutPageTemplateSettingPersistence;
	}

	/**
	 * Sets the layout page template setting persistence.
	 *
	 * @param layoutPageTemplateSettingPersistence the layout page template setting persistence
	 */
	public void setLayoutPageTemplateSettingPersistence(
		LayoutPageTemplateSettingPersistence layoutPageTemplateSettingPersistence) {
		this.layoutPageTemplateSettingPersistence = layoutPageTemplateSettingPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.layout.page.template.model.LayoutPageTemplateSetting",
			layoutPageTemplateSettingLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.layout.page.template.model.LayoutPageTemplateSetting");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutPageTemplateSettingLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LayoutPageTemplateSetting.class;
	}

	protected String getModelClassName() {
		return LayoutPageTemplateSetting.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = layoutPageTemplateSettingPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LayoutPageTemplateSettingLocalService.class)
	protected LayoutPageTemplateSettingLocalService layoutPageTemplateSettingLocalService;
	@BeanReference(type = LayoutPageTemplateSettingPersistence.class)
	protected LayoutPageTemplateSettingPersistence layoutPageTemplateSettingPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}