/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryRel;
import com.liferay.asset.entry.rel.model.AssetEntryRelModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetEntryRel service. Represents a row in the &quot;AssetEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssetEntryRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryRelImpl
 * @see AssetEntryRel
 * @see AssetEntryRelModel
 * @generated
 */
@ProviderType
public class AssetEntryRelModelImpl extends BaseModelImpl<AssetEntryRel>
	implements AssetEntryRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry rel model instance should use the {@link AssetEntryRel} interface instead.
	 */
	public static final String TABLE_NAME = "AssetEntryRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetEntryRelId", Types.BIGINT },
			{ "assetEntryId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("assetEntryRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssetEntryRel (assetEntryRelId LONG not null primary key,assetEntryId LONG,classNameId LONG,classPK LONG)";
	public static final String TABLE_SQL_DROP = "drop table AssetEntryRel";
	public static final String ORDER_BY_JPQL = " ORDER BY assetEntryRel.assetEntryRelId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssetEntryRel.assetEntryRelId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.asset.entry.rel.model.AssetEntryRel"),
			true);
	public static final long ASSETENTRYID_COLUMN_BITMASK = 1L;
	public static final long CLASSNAMEID_COLUMN_BITMASK = 2L;
	public static final long ASSETENTRYRELID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.asset.entry.rel.model.AssetEntryRel"));

	public AssetEntryRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetEntryRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetEntryRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetEntryRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetEntryRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetEntryRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetEntryRelId", getAssetEntryRelId());
		attributes.put("assetEntryId", getAssetEntryId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetEntryRelId = (Long)attributes.get("assetEntryRelId");

		if (assetEntryRelId != null) {
			setAssetEntryRelId(assetEntryRelId);
		}

		Long assetEntryId = (Long)attributes.get("assetEntryId");

		if (assetEntryId != null) {
			setAssetEntryId(assetEntryId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}
	}

	@Override
	public long getAssetEntryRelId() {
		return _assetEntryRelId;
	}

	@Override
	public void setAssetEntryRelId(long assetEntryRelId) {
		_assetEntryRelId = assetEntryRelId;
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAssetEntryId) {
			_setOriginalAssetEntryId = true;

			_originalAssetEntryId = _assetEntryId;
		}

		_assetEntryId = assetEntryId;
	}

	public long getOriginalAssetEntryId() {
		return _originalAssetEntryId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssetEntryRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetEntryRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetEntryRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetEntryRelImpl assetEntryRelImpl = new AssetEntryRelImpl();

		assetEntryRelImpl.setAssetEntryRelId(getAssetEntryRelId());
		assetEntryRelImpl.setAssetEntryId(getAssetEntryId());
		assetEntryRelImpl.setClassNameId(getClassNameId());
		assetEntryRelImpl.setClassPK(getClassPK());

		assetEntryRelImpl.resetOriginalValues();

		return assetEntryRelImpl;
	}

	@Override
	public int compareTo(AssetEntryRel assetEntryRel) {
		long primaryKey = assetEntryRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetEntryRel)) {
			return false;
		}

		AssetEntryRel assetEntryRel = (AssetEntryRel)obj;

		long primaryKey = assetEntryRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssetEntryRelModelImpl assetEntryRelModelImpl = this;

		assetEntryRelModelImpl._originalAssetEntryId = assetEntryRelModelImpl._assetEntryId;

		assetEntryRelModelImpl._setOriginalAssetEntryId = false;

		assetEntryRelModelImpl._originalClassNameId = assetEntryRelModelImpl._classNameId;

		assetEntryRelModelImpl._setOriginalClassNameId = false;

		assetEntryRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetEntryRel> toCacheModel() {
		AssetEntryRelCacheModel assetEntryRelCacheModel = new AssetEntryRelCacheModel();

		assetEntryRelCacheModel.assetEntryRelId = getAssetEntryRelId();

		assetEntryRelCacheModel.assetEntryId = getAssetEntryId();

		assetEntryRelCacheModel.classNameId = getClassNameId();

		assetEntryRelCacheModel.classPK = getClassPK();

		return assetEntryRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{assetEntryRelId=");
		sb.append(getAssetEntryRelId());
		sb.append(", assetEntryId=");
		sb.append(getAssetEntryId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.asset.entry.rel.model.AssetEntryRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetEntryRelId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetEntryId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssetEntryRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetEntryRel.class
		};
	private long _assetEntryRelId;
	private long _assetEntryId;
	private long _originalAssetEntryId;
	private boolean _setOriginalAssetEntryId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _columnBitmask;
	private AssetEntryRel _escapedModel;
}