/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.layout.service.model.LayoutFragment;
import com.liferay.layout.service.model.LayoutFragmentModel;
import com.liferay.layout.service.model.LayoutFragmentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LayoutFragment service. Represents a row in the &quot;LayoutFragment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LayoutFragmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutFragmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutFragmentImpl
 * @see LayoutFragment
 * @see LayoutFragmentModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LayoutFragmentModelImpl extends BaseModelImpl<LayoutFragment>
	implements LayoutFragmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout fragment model instance should use the {@link LayoutFragment} interface instead.
	 */
	public static final String TABLE_NAME = "LayoutFragment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "layoutFragmentId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "plid", Types.BIGINT },
			{ "fragmentEntryId", Types.BIGINT },
			{ "css", Types.VARCHAR },
			{ "html", Types.VARCHAR },
			{ "js", Types.VARCHAR },
			{ "position", Types.INTEGER },
			{ "typeSettings", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("layoutFragmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("css", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("html", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("js", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("typeSettings", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table LayoutFragment (layoutFragmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,plid LONG,fragmentEntryId LONG,css STRING null,html STRING null,js STRING null,position INTEGER,typeSettings VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table LayoutFragment";
	public static final String ORDER_BY_JPQL = " ORDER BY layoutFragment.position ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LayoutFragment.position ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.layout.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.layout.service.model.LayoutFragment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.layout.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.layout.service.model.LayoutFragment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.layout.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.layout.service.model.LayoutFragment"),
			true);
	public static final long FRAGMENTENTRYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long PLID_COLUMN_BITMASK = 4L;
	public static final long POSITION_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LayoutFragment toModel(LayoutFragmentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LayoutFragment model = new LayoutFragmentImpl();

		model.setLayoutFragmentId(soapModel.getLayoutFragmentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPlid(soapModel.getPlid());
		model.setFragmentEntryId(soapModel.getFragmentEntryId());
		model.setCss(soapModel.getCss());
		model.setHtml(soapModel.getHtml());
		model.setJs(soapModel.getJs());
		model.setPosition(soapModel.getPosition());
		model.setTypeSettings(soapModel.getTypeSettings());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LayoutFragment> toModels(LayoutFragmentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LayoutFragment> models = new ArrayList<LayoutFragment>(soapModels.length);

		for (LayoutFragmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.layout.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.layout.service.model.LayoutFragment"));

	public LayoutFragmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutFragmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutFragmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutFragmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutFragment.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutFragment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("layoutFragmentId", getLayoutFragmentId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("plid", getPlid());
		attributes.put("fragmentEntryId", getFragmentEntryId());
		attributes.put("css", getCss());
		attributes.put("html", getHtml());
		attributes.put("js", getJs());
		attributes.put("position", getPosition());
		attributes.put("typeSettings", getTypeSettings());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long layoutFragmentId = (Long)attributes.get("layoutFragmentId");

		if (layoutFragmentId != null) {
			setLayoutFragmentId(layoutFragmentId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long plid = (Long)attributes.get("plid");

		if (plid != null) {
			setPlid(plid);
		}

		Long fragmentEntryId = (Long)attributes.get("fragmentEntryId");

		if (fragmentEntryId != null) {
			setFragmentEntryId(fragmentEntryId);
		}

		String css = (String)attributes.get("css");

		if (css != null) {
			setCss(css);
		}

		String html = (String)attributes.get("html");

		if (html != null) {
			setHtml(html);
		}

		String js = (String)attributes.get("js");

		if (js != null) {
			setJs(js);
		}

		Integer position = (Integer)attributes.get("position");

		if (position != null) {
			setPosition(position);
		}

		String typeSettings = (String)attributes.get("typeSettings");

		if (typeSettings != null) {
			setTypeSettings(typeSettings);
		}
	}

	@JSON
	@Override
	public long getLayoutFragmentId() {
		return _layoutFragmentId;
	}

	@Override
	public void setLayoutFragmentId(long layoutFragmentId) {
		_layoutFragmentId = layoutFragmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_columnBitmask |= PLID_COLUMN_BITMASK;

		if (!_setOriginalPlid) {
			_setOriginalPlid = true;

			_originalPlid = _plid;
		}

		_plid = plid;
	}

	public long getOriginalPlid() {
		return _originalPlid;
	}

	@JSON
	@Override
	public long getFragmentEntryId() {
		return _fragmentEntryId;
	}

	@Override
	public void setFragmentEntryId(long fragmentEntryId) {
		_columnBitmask |= FRAGMENTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFragmentEntryId) {
			_setOriginalFragmentEntryId = true;

			_originalFragmentEntryId = _fragmentEntryId;
		}

		_fragmentEntryId = fragmentEntryId;
	}

	public long getOriginalFragmentEntryId() {
		return _originalFragmentEntryId;
	}

	@JSON
	@Override
	public String getCss() {
		if (_css == null) {
			return "";
		}
		else {
			return _css;
		}
	}

	@Override
	public void setCss(String css) {
		_css = css;
	}

	@JSON
	@Override
	public String getHtml() {
		if (_html == null) {
			return "";
		}
		else {
			return _html;
		}
	}

	@Override
	public void setHtml(String html) {
		_html = html;
	}

	@JSON
	@Override
	public String getJs() {
		if (_js == null) {
			return "";
		}
		else {
			return _js;
		}
	}

	@Override
	public void setJs(String js) {
		_js = js;
	}

	@JSON
	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		_columnBitmask = -1L;

		_position = position;
	}

	@JSON
	@Override
	public String getTypeSettings() {
		if (_typeSettings == null) {
			return "";
		}
		else {
			return _typeSettings;
		}
	}

	@Override
	public void setTypeSettings(String typeSettings) {
		_typeSettings = typeSettings;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LayoutFragment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LayoutFragment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LayoutFragment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutFragmentImpl layoutFragmentImpl = new LayoutFragmentImpl();

		layoutFragmentImpl.setLayoutFragmentId(getLayoutFragmentId());
		layoutFragmentImpl.setGroupId(getGroupId());
		layoutFragmentImpl.setCompanyId(getCompanyId());
		layoutFragmentImpl.setUserId(getUserId());
		layoutFragmentImpl.setUserName(getUserName());
		layoutFragmentImpl.setCreateDate(getCreateDate());
		layoutFragmentImpl.setModifiedDate(getModifiedDate());
		layoutFragmentImpl.setPlid(getPlid());
		layoutFragmentImpl.setFragmentEntryId(getFragmentEntryId());
		layoutFragmentImpl.setCss(getCss());
		layoutFragmentImpl.setHtml(getHtml());
		layoutFragmentImpl.setJs(getJs());
		layoutFragmentImpl.setPosition(getPosition());
		layoutFragmentImpl.setTypeSettings(getTypeSettings());

		layoutFragmentImpl.resetOriginalValues();

		return layoutFragmentImpl;
	}

	@Override
	public int compareTo(LayoutFragment layoutFragment) {
		int value = 0;

		if (getPosition() < layoutFragment.getPosition()) {
			value = -1;
		}
		else if (getPosition() > layoutFragment.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutFragment)) {
			return false;
		}

		LayoutFragment layoutFragment = (LayoutFragment)obj;

		long primaryKey = layoutFragment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LayoutFragmentModelImpl layoutFragmentModelImpl = this;

		layoutFragmentModelImpl._originalGroupId = layoutFragmentModelImpl._groupId;

		layoutFragmentModelImpl._setOriginalGroupId = false;

		layoutFragmentModelImpl._setModifiedDate = false;

		layoutFragmentModelImpl._originalPlid = layoutFragmentModelImpl._plid;

		layoutFragmentModelImpl._setOriginalPlid = false;

		layoutFragmentModelImpl._originalFragmentEntryId = layoutFragmentModelImpl._fragmentEntryId;

		layoutFragmentModelImpl._setOriginalFragmentEntryId = false;

		layoutFragmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutFragment> toCacheModel() {
		LayoutFragmentCacheModel layoutFragmentCacheModel = new LayoutFragmentCacheModel();

		layoutFragmentCacheModel.layoutFragmentId = getLayoutFragmentId();

		layoutFragmentCacheModel.groupId = getGroupId();

		layoutFragmentCacheModel.companyId = getCompanyId();

		layoutFragmentCacheModel.userId = getUserId();

		layoutFragmentCacheModel.userName = getUserName();

		String userName = layoutFragmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutFragmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutFragmentCacheModel.createDate = createDate.getTime();
		}
		else {
			layoutFragmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutFragmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			layoutFragmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		layoutFragmentCacheModel.plid = getPlid();

		layoutFragmentCacheModel.fragmentEntryId = getFragmentEntryId();

		layoutFragmentCacheModel.css = getCss();

		String css = layoutFragmentCacheModel.css;

		if ((css != null) && (css.length() == 0)) {
			layoutFragmentCacheModel.css = null;
		}

		layoutFragmentCacheModel.html = getHtml();

		String html = layoutFragmentCacheModel.html;

		if ((html != null) && (html.length() == 0)) {
			layoutFragmentCacheModel.html = null;
		}

		layoutFragmentCacheModel.js = getJs();

		String js = layoutFragmentCacheModel.js;

		if ((js != null) && (js.length() == 0)) {
			layoutFragmentCacheModel.js = null;
		}

		layoutFragmentCacheModel.position = getPosition();

		layoutFragmentCacheModel.typeSettings = getTypeSettings();

		String typeSettings = layoutFragmentCacheModel.typeSettings;

		if ((typeSettings != null) && (typeSettings.length() == 0)) {
			layoutFragmentCacheModel.typeSettings = null;
		}

		return layoutFragmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{layoutFragmentId=");
		sb.append(getLayoutFragmentId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", plid=");
		sb.append(getPlid());
		sb.append(", fragmentEntryId=");
		sb.append(getFragmentEntryId());
		sb.append(", css=");
		sb.append(getCss());
		sb.append(", html=");
		sb.append(getHtml());
		sb.append(", js=");
		sb.append(getJs());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append(", typeSettings=");
		sb.append(getTypeSettings());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.layout.service.model.LayoutFragment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>layoutFragmentId</column-name><column-value><![CDATA[");
		sb.append(getLayoutFragmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>plid</column-name><column-value><![CDATA[");
		sb.append(getPlid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fragmentEntryId</column-name><column-value><![CDATA[");
		sb.append(getFragmentEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>css</column-name><column-value><![CDATA[");
		sb.append(getCss());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>html</column-name><column-value><![CDATA[");
		sb.append(getHtml());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>js</column-name><column-value><![CDATA[");
		sb.append(getJs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeSettings</column-name><column-value><![CDATA[");
		sb.append(getTypeSettings());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LayoutFragment.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LayoutFragment.class
		};
	private long _layoutFragmentId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _plid;
	private long _originalPlid;
	private boolean _setOriginalPlid;
	private long _fragmentEntryId;
	private long _originalFragmentEntryId;
	private boolean _setOriginalFragmentEntryId;
	private String _css;
	private String _html;
	private String _js;
	private int _position;
	private String _typeSettings;
	private long _columnBitmask;
	private LayoutFragment _escapedModel;
}