/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryRel;
import com.liferay.asset.entry.rel.service.AssetEntryRelLocalService;
import com.liferay.asset.entry.rel.service.persistence.AssetEntryRelPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.entry.rel.service.impl.AssetEntryRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.entry.rel.service.impl.AssetEntryRelLocalServiceImpl
 * @see com.liferay.asset.entry.rel.service.AssetEntryRelLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetEntryRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AssetEntryRelLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.entry.rel.service.AssetEntryRelLocalServiceUtil} to access the asset entry rel local service.
	 */

	/**
	 * Adds the asset entry rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryRel the asset entry rel
	 * @return the asset entry rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryRel addAssetEntryRel(AssetEntryRel assetEntryRel) {
		assetEntryRel.setNew(true);

		return assetEntryRelPersistence.update(assetEntryRel);
	}

	/**
	 * Creates a new asset entry rel with the primary key. Does not add the asset entry rel to the database.
	 *
	 * @param assetEntryRelId the primary key for the new asset entry rel
	 * @return the new asset entry rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetEntryRel createAssetEntryRel(long assetEntryRelId) {
		return assetEntryRelPersistence.create(assetEntryRelId);
	}

	/**
	 * Deletes the asset entry rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryRelId the primary key of the asset entry rel
	 * @return the asset entry rel that was removed
	 * @throws PortalException if a asset entry rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryRel deleteAssetEntryRel(long assetEntryRelId)
		throws PortalException {
		return assetEntryRelPersistence.remove(assetEntryRelId);
	}

	/**
	 * Deletes the asset entry rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryRel the asset entry rel
	 * @return the asset entry rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryRel deleteAssetEntryRel(AssetEntryRel assetEntryRel) {
		return assetEntryRelPersistence.remove(assetEntryRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AssetEntryRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntryRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetEntryRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetEntryRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntryRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetEntryRelPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AssetEntryRel fetchAssetEntryRel(long assetEntryRelId) {
		return assetEntryRelPersistence.fetchByPrimaryKey(assetEntryRelId);
	}

	/**
	 * Returns the asset entry rel with the primary key.
	 *
	 * @param assetEntryRelId the primary key of the asset entry rel
	 * @return the asset entry rel
	 * @throws PortalException if a asset entry rel with the primary key could not be found
	 */
	@Override
	public AssetEntryRel getAssetEntryRel(long assetEntryRelId)
		throws PortalException {
		return assetEntryRelPersistence.findByPrimaryKey(assetEntryRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetEntryRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetEntryRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetEntryRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetEntryRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetEntryRelLocalService.deleteAssetEntryRel((AssetEntryRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetEntryRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asset entry rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry rels
	 * @param end the upper bound of the range of asset entry rels (not inclusive)
	 * @return the range of asset entry rels
	 */
	@Override
	public List<AssetEntryRel> getAssetEntryRels(int start, int end) {
		return assetEntryRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry rels.
	 *
	 * @return the number of asset entry rels
	 */
	@Override
	public int getAssetEntryRelsCount() {
		return assetEntryRelPersistence.countAll();
	}

	/**
	 * Updates the asset entry rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryRel the asset entry rel
	 * @return the asset entry rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryRel updateAssetEntryRel(AssetEntryRel assetEntryRel) {
		return assetEntryRelPersistence.update(assetEntryRel);
	}

	/**
	 * Returns the asset entry rel local service.
	 *
	 * @return the asset entry rel local service
	 */
	public AssetEntryRelLocalService getAssetEntryRelLocalService() {
		return assetEntryRelLocalService;
	}

	/**
	 * Sets the asset entry rel local service.
	 *
	 * @param assetEntryRelLocalService the asset entry rel local service
	 */
	public void setAssetEntryRelLocalService(
		AssetEntryRelLocalService assetEntryRelLocalService) {
		this.assetEntryRelLocalService = assetEntryRelLocalService;
	}

	/**
	 * Returns the asset entry rel persistence.
	 *
	 * @return the asset entry rel persistence
	 */
	public AssetEntryRelPersistence getAssetEntryRelPersistence() {
		return assetEntryRelPersistence;
	}

	/**
	 * Sets the asset entry rel persistence.
	 *
	 * @param assetEntryRelPersistence the asset entry rel persistence
	 */
	public void setAssetEntryRelPersistence(
		AssetEntryRelPersistence assetEntryRelPersistence) {
		this.assetEntryRelPersistence = assetEntryRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.asset.entry.rel.model.AssetEntryRel",
			assetEntryRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.asset.entry.rel.model.AssetEntryRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntryRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntryRel.class;
	}

	protected String getModelClassName() {
		return AssetEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetEntryRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetEntryRelLocalService.class)
	protected AssetEntryRelLocalService assetEntryRelLocalService;
	@BeanReference(type = AssetEntryRelPersistence.class)
	protected AssetEntryRelPersistence assetEntryRelPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}