/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LayoutFragment service. Represents a row in the &quot;LayoutFragment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.layout.service.model.impl.LayoutFragmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.layout.service.model.impl.LayoutFragmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutFragment
 * @see com.liferay.layout.service.model.impl.LayoutFragmentImpl
 * @see com.liferay.layout.service.model.impl.LayoutFragmentModelImpl
 * @generated
 */
@ProviderType
public interface LayoutFragmentModel extends BaseModel<LayoutFragment>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout fragment model instance should use the {@link LayoutFragment} interface instead.
	 */

	/**
	 * Returns the primary key of this layout fragment.
	 *
	 * @return the primary key of this layout fragment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout fragment.
	 *
	 * @param primaryKey the primary key of this layout fragment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the layout fragment ID of this layout fragment.
	 *
	 * @return the layout fragment ID of this layout fragment
	 */
	public long getLayoutFragmentId();

	/**
	 * Sets the layout fragment ID of this layout fragment.
	 *
	 * @param layoutFragmentId the layout fragment ID of this layout fragment
	 */
	public void setLayoutFragmentId(long layoutFragmentId);

	/**
	 * Returns the group ID of this layout fragment.
	 *
	 * @return the group ID of this layout fragment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this layout fragment.
	 *
	 * @param groupId the group ID of this layout fragment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout fragment.
	 *
	 * @return the company ID of this layout fragment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout fragment.
	 *
	 * @param companyId the company ID of this layout fragment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this layout fragment.
	 *
	 * @return the user ID of this layout fragment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this layout fragment.
	 *
	 * @param userId the user ID of this layout fragment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layout fragment.
	 *
	 * @return the user uuid of this layout fragment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this layout fragment.
	 *
	 * @param userUuid the user uuid of this layout fragment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this layout fragment.
	 *
	 * @return the user name of this layout fragment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this layout fragment.
	 *
	 * @param userName the user name of this layout fragment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this layout fragment.
	 *
	 * @return the create date of this layout fragment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout fragment.
	 *
	 * @param createDate the create date of this layout fragment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout fragment.
	 *
	 * @return the modified date of this layout fragment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout fragment.
	 *
	 * @param modifiedDate the modified date of this layout fragment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plid of this layout fragment.
	 *
	 * @return the plid of this layout fragment
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout fragment.
	 *
	 * @param plid the plid of this layout fragment
	 */
	public void setPlid(long plid);

	/**
	 * Returns the fragment entry ID of this layout fragment.
	 *
	 * @return the fragment entry ID of this layout fragment
	 */
	public long getFragmentEntryId();

	/**
	 * Sets the fragment entry ID of this layout fragment.
	 *
	 * @param fragmentEntryId the fragment entry ID of this layout fragment
	 */
	public void setFragmentEntryId(long fragmentEntryId);

	/**
	 * Returns the css of this layout fragment.
	 *
	 * @return the css of this layout fragment
	 */
	@AutoEscape
	public String getCss();

	/**
	 * Sets the css of this layout fragment.
	 *
	 * @param css the css of this layout fragment
	 */
	public void setCss(String css);

	/**
	 * Returns the html of this layout fragment.
	 *
	 * @return the html of this layout fragment
	 */
	@AutoEscape
	public String getHtml();

	/**
	 * Sets the html of this layout fragment.
	 *
	 * @param html the html of this layout fragment
	 */
	public void setHtml(String html);

	/**
	 * Returns the js of this layout fragment.
	 *
	 * @return the js of this layout fragment
	 */
	@AutoEscape
	public String getJs();

	/**
	 * Sets the js of this layout fragment.
	 *
	 * @param js the js of this layout fragment
	 */
	public void setJs(String js);

	/**
	 * Returns the position of this layout fragment.
	 *
	 * @return the position of this layout fragment
	 */
	public int getPosition();

	/**
	 * Sets the position of this layout fragment.
	 *
	 * @param position the position of this layout fragment
	 */
	public void setPosition(int position);

	/**
	 * Returns the type settings of this layout fragment.
	 *
	 * @return the type settings of this layout fragment
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this layout fragment.
	 *
	 * @param typeSettings the type settings of this layout fragment
	 */
	public void setTypeSettings(String typeSettings);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LayoutFragment layoutFragment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LayoutFragment> toCacheModel();

	@Override
	public LayoutFragment toEscapedModel();

	@Override
	public LayoutFragment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}